trainer:
  accelerator: auto
  devices: 1
  max_epochs: 10
  log_every_n_steps: 10

optimizer:
  name: adam
  lr: 1e-3

batch_size:
  train: 64
  eval: 128

dataloader:
  num_workers: 4
  pin_memory: true

monitoring:
  val_metric: val_v_measure_pred
  mode: max
